### ISSUE TITLE
Stripe: re-subscribing while 'unpaid' results in two subscriptions

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#962] opened 2017-02-13 20:46 UTC
If a user with an existing `unpaid` subscription in Stripe and subscribes to a new plan then both subscriptions get activated, resulting in multiple charges. 

For example, an old user's subscription expired due to failing payments and Stripe set the plan to `unpaid` (depending on Stripe settings). 

That user comes back later and subscribes anew, unaware their old plan is simply delinquent. 

Upon resubscribing the user now has two subscriptions in Stripe, both of which are active and have just been billed. 

---

There needs to be some logic to account for users resubscribing while having a delinquent plan. 

*A similar issue can also happen when delinquent users update their card details, unaware that doing so will cause the unpaid subscription to reactivate.*

**Comment by mindctrl** [comment] 2017-03-10 23:58
If unpaid invoices continue to accumulate due to the Stripe account settings, we'll want to make sure they don't all get paid unexpectedly. I don't think they would, but something to confirm.

**Comment by nosegraze** [comment] 2017-03-15 15:37
We do have this:

```php
// clean up any past due or unpaid subscriptions before upgrading/downgrading
foreach( $customer->subscriptions->all()->data as $subscription ) {

	// check if we are renewing an existing subscription. This should not ever be 'active', if it is Stripe
	// will do nothing. If it is 'past_due' the most recent invoice will be paid and the subscription will become active
	if ( $subscription->plan->id == $plan_id && in_array( $subscription->status, array( 'active', 'past_due' ) ) ) {
		continue;
	}

	// remove any subscriptions that are past_due or inactive
	if ( in_array( $subscription->status, array( 'past_due', 'unpaid' ) ) ) {
		$subscription->cancel();
	}
}
```

Is there an issue with that first `if` statement where we `continue`? Or is there something else we need to be looking for?

**Comment by mindctrl** [comment] 2017-03-15 15:45
re: unpaid invoices that accumulate... Stripe appears to be paying the back past due ones in my test.

I updated an expired member that had a bunch of past due invoices. Stripe is paying all the past due invoices every day, 2-3 of them each day, since I resubscribed with a valid card on file.

We'll need to account for that in some way I think, for cases when the Stripe account is set up to not cancel after x # of failed billings.

**Comment by mindctrl** [comment] 2017-04-07 02:17
Response from Stripe re: unpaid invoices:

> Your stored cards will continue to work even if the card number or expiry date changes—Stripe works directly with card networks so that your customers can continue using your service without interruption. Here's a support article on that subject:
>
> https://stripe.com/blog/smarter-saved-cards
>
> When it comes to recurring payments/subscriptions, the typical reasons for payment failure would be due to insufficient funds or if the card was closed with no replacement. In these instances, we will follow through with your selected settings ( retry 1, 3, 5, and cancel).

**Comment by carter2422** [comment] 2017-04-07 02:33
>We'll need to account for that in some way I think, for cases when the Stripe account is set up to not cancel after x # of failed billings. 

This is precisely the scenario that I run into. We never auto-cancel delinquent plans so that we can recover them via dunning efforts.

**Comment by nosegraze** [comment] 2017-04-14 15:04
@carter2422 We're going to start adding metadata to subscriptions to help us identify them as being from RCP. Then whenever a new subscription is created in RCP, we'll first cancel _all_ subscriptions that have the matching RCP metadata. Do you think that would work for you? This wouldn't help any users who currently have the problem, but would hopefully prevent it moving forward.

**Comment by mindctrl** [comment] 2017-04-17 13:59
Milestoning this for 2.9, which is scheduled for around the end of the month if all goes well. That'll give us time to get feedback and do some testing. 2.8.5 is going out today.

**Comment by mindctrl** [comment] 2017-04-18 15:13
I just saw this issue on a customer site. Just to reiterate, steps to reproduce:

- log in as member with past due subscription in Stripe (member is expired in RCP)
- go to registration form, purchase a **different** subscription

The original doesn't get cancelled in Stripe, resulting in two subscriptions. The past due one in Stripe goes active because of the new payment card.

There's something not right in [that loop](https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-286781507).

**Comment by carter2422** [comment] 2017-04-18 15:54
>>> @carter2422 We're going to start adding metadata to subscriptions to help us identify them as being from RCP. Then whenever a new subscription is created in RCP, we'll first cancel all subscriptions that have the matching RCP metadata. Do you think that would work for you? This wouldn't help any users who currently have the problem, but would hopefully prevent it moving forward.

@nosegraze I think that should work for some, but it seems a bit limited in that customers with existing unpaid subscriptions, without meta, would still result in duplicate subscriptions.

**Comment by pippinsplugins** [comment] 2017-04-18 16:49
I'm not sure there's a way to account for those existing subscriptions without potentially cancelling subscriptions created in Stripe from other systems.

**Comment by mindctrl** [comment] 2017-04-19 14:53
Short of fetching all the subscriptions and doing a string search for plan names that match the level names in RCP, I don't know of another way to do it.

**Comment by nosegraze** [comment] 2017-06-07 13:09
PR: #1270

The PR won't fix [this problem](https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-294877038) though since that's with a different subscription ID. How do we want to handle that? I'm trying to keep in mind that we'll be allowing multiple subscriptions in the future, so cancelling _everything_ isn't really a good approach since we'd just have to change that later.

**Comment by mindctrl** [comment] 2017-07-25 13:59
While testing an upgrade of an active member, I got the following error:
```
Status: 404

Message: No such subscription: sub_B5N8L2Zq7ltemV
```

The sub was cancelled, but it tried to cancel twice which resulted in an error the second time.

**Comment by nosegraze** [comment] 2017-07-25 14:37
Hmm maybe we should do this now https://github.com/restrictcontentpro/restrict-content-pro/issues/1292

**Comment by mindctrl** [comment] 2017-07-25 15:53
Let's either push this to the second beta or 2.9.1 so we can do a little more testing. Thoughts?

**Comment by nosegraze** [comment] 2017-09-05 14:02
Updated PR to fix [this problem](https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-317746488).

**Comment by mindctrl** [comment] 2017-09-05 16:48
I just got this error when upgrading a user that had more than one sub in Stripe (which was due to [this](https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-294877038)).

> An error occurred

> Status: 400

> Message: Customer has 2 (>1) active subscriptions. Must specify which subscription (/v1/customers/:id/subscriptions/:subscription_id)

**Comment by nosegraze** [comment] 2017-09-05 17:14
Do you know where in the code that error got triggered? I'm wondering if you ran into [this line](https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-member.php#L565) (which happens when there's no merchant subscription ID in your profile).

**Comment by mindctrl** [comment] 2017-09-05 17:25
I think that was it too. This user account doesn't have a merchant sub ID in usermeta.

**Comment by nosegraze** [comment] 2017-09-05 17:30
Okay I think that's unrelated to this PR then. Should definitely still be fixed though. We need to go through and remove all the `wp_die()` functions from that method. But that means we'll need a better way to handle and display errors related to cancellations in both the front-end and admin area. That's probably best to tackle in a separate issue. Maybe make https://github.com/restrictcontentpro/restrict-content-pro/issues/1292 more generic.

**Comment by mindctrl** [comment] 2017-09-15 15:56
@thomasfw did you happen to test this on your site?

**Comment by thomasfw** [comment] 2017-09-25 22:21
@mindctrl we're still on version 2.8.6 and were planning on waiting for the release containing this fix before upgrading. We have some refactoring to do before we upgrade to >2.9.

Thats said, it looks like the current patch will only prevent this happening in future, and [won't provide a fix for anyone who's currently dealing with it?](https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-294169743) Our subscription length is yearly, so the majority of payments do not contain the new metadata.

Your idea of looping through the user's existing subscriptions and doing a string match on the rcp level names isn't as pretty, but if it's the only proper way to resolve this then it should be implemented. You could also check each `$subscription_object->status`, and only cancel if it's set to `past_due`, `canceled`, or `unpaid`. This way it'll remain compatible when you introduce the ability to have more than one subscription, as active subscriptions will be left alone.

> "If subscription `billing=charge_automatically` it becomes `past_due` when payment to renew it fails and `canceled` or `unpaid` (depending on your subscriptions settings) when Stripe has exhausted all payment retry attempts." - [subscription_object](https://stripe.com/docs/api#subscription_object)

**Comment by mindctrl** [comment] 2017-10-13 18:28
re: this comment: https://github.com/restrictcontentpro/restrict-content-pro/issues/962#issuecomment-294877038

I think for now we could do something like this, while we're looping through those subs:
```
if ( ! empty( $subscription->plan->name ) ) {

	global $rcp_levels_db;

	$level = $rcp_levels_db->get_level_by( 'name', $subscription->plan->name );

	// Make sure this subscription is for an RCP subscription level before moving forward
	if ( empty( $level ) ) {
		continue;
	}
	
	if ( $subscription->plan->name !== $member->get_pending_subscription_name() ) {
		$subscription->cancel();
		$cancelled_subscriptions[] = $subscription->id;
	}
}
```

This would cancel subscriptions whose name doesn't match the pending subscription, but only if the plan name matches a level name in RCP.

Need someone to check my thinking on that. Today's my no ☕️  day.

**Comment by pippinsplugins** [comment] 2017-10-13 18:38
That looks fine, though that logic should only run if the metadata is also missing.

1. If meta data is present, rely on that for plan detection.
2. If meta data is missing, rely on name comparison.

**Comment by nosegraze** [comment] 2017-10-16 12:08
So does that completely replace this bit?

```php
// check if we are renewing an existing subscription. This should not ever be 'active', if it is Stripe
// will do nothing. If it is 'past_due' the most recent invoice will be paid and the subscription will become active
if ( $subscription->plan->id == $plan_id && in_array( $subscription->status, array( 'active', 'past_due' ) ) ) {
	continue;
}

// remove any subscriptions that are past_due or inactive
if ( in_array( $subscription->status, array( 'past_due', 'unpaid' ) ) ) {
	$cancelled_subscriptions[] = $subscription->id;
	$subscription->cancel();
}
```

Or do we still need to keep this for some reason too?

**Comment by mindctrl** [comment] 2017-10-16 13:56
I _think_ we can remove that.

**Comment by nosegraze** [comment] 2017-10-16 15:22
Just had a thought...

> This would cancel subscriptions whose name doesn't match the pending subscription

I don't think this would cover a scenario where:

- User is subscribed to Plan A.
- Subscription expires due to failed card, etc.
- User goes back through registration form to renew Plan A again.

That's actually the most common scenario I've seen being reported (renewal vs an upgrade/downgrade).

In that case, this `if` statement would fail since the plan names would actually be the same:

```php
if ( $subscription->plan->name !== $member->get_pending_subscription_name() ) {
```

Is there any harm in removing that `if` statement and just cancelling any Stripe plan where the name matches any RCP subscription level? Obviously that won't be doable if/when we add multiple subscription support, but for now is there any problem with that?

**Comment by mindctrl** [comment] 2017-10-16 15:26
Ah yes, good catch. For now I don't think there would be an issue with cancelling all existing subs that match an RCP level.

**Comment by mindctrl** [comment] 2017-10-16 15:37
@nosegraze not sure what just happened, but your PR now says it's set to merge into `release/2.9` and it's showing a ton of commits now.

**Comment by mindctrl** [comment] 2017-10-16 15:39
Just closed it. Don't want to risk polluting the git history and/or breaking something. Let's open a new PR.

**Comment by nosegraze** [comment] 2017-10-16 15:45
Huh weird. New PR: https://github.com/restrictcontentpro/restrict-content-pro/pull/1502

**Closed** 2017-10-16 19:14 UTC
Labels: bug, has PR
