### ISSUE TITLE
Add Authorize.net gateway

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#204] opened 2015-07-06 00:22 UTC
Authorize.net should be supported.

**Comment by mindctrl** [comment] 2015-09-30 17:08
Someone just said they wanted this in EDD support. :laughing:

**Comment by pippinsplugins** [comment] 2015-10-01 17:52
:+1:

**Comment by pippinsplugins** [comment] 2016-07-31 21:23
Another request https://secure.helpscout.net/conversation/233208790/39096/?folderId=841776

**Comment by mindctrl** [comment] 2016-08-23 17:25
Another request: https://secure.helpscout.net/conversation/241873426/40582/?folderId=841787

**Comment by tnorthcutt** [comment] 2016-12-27 15:45
Just got an email from someone asking me to build this as well, FYI. @pippinsplugins is this on the near horizon?

**Comment by pippinsplugins** [comment] 2016-12-27 16:02
@tnorthcutt I have it started and am hoping to finish it for 2.7.

**Comment by pippinsplugins** [comment] 2017-01-20 17:46
Not finished yet but we're ready for some initial testing here!

**Comment by pippinsplugins** [comment] 2017-01-20 21:14
Ok we're up and running! Still things left to do but signups can be tested now.

Left to do:

- Card update form
- Cancellation processing
- Payment logging

**Comment by nosegraze** [comment] 2017-01-23 14:12
This is my very very first time using Authorize.net at all, so bear with me. :D 

There's a fatal error on this line when payment fails:
```
$error = $response->getMessages()->getMessage()[0]->getCode() . ' ' . $response->getMessages()->getMessage()[0]->getText();
```
> Call to undefined method AuthorizeNetARB_Response::getMessages()

The error I was getting was:

> Interval Length must be a value from 7 through 365 for day based subscriptions

I had my subscription set to 1 day. So if this is a limitation on Authorize.net we should mention that in the docs. But the actual code needs to be fixed as well.

---

I signed up for one subscription level (non-recurring). Then I tried to sign up for it again and got an error that I can't create a duplicate subscription. I'm not sure if that's expected behaviour or not. I feel like you can do this successfully with the other gateways. I was trying to "renew" before I was actually expired and I just want to make sure this won't be a problem if someone does try to renew the same subscription again manually when their plan expires.

I also got this same error when trying to change to a different subscription, but then I tried again with a different "name on card" and it went through. But then I tried it _again_ and couldn't get the error to pop back up..

---

When I look in Authorize.net, all my test payments are marked as "pending transactions" or "scheduled payments". Is that expected? (I'm also not getting any payments logged in RCP but it sounds like you haven't done that part yet.)

---

In the `process_webhooks()` method there are a few undefined variables:

```
$member->renew( $true );
$payments->insert( $payment_data );
```

`$true` and `$payments` are both undefined.

---

I signed up with a recurring subscription, then upgraded to a different plan. The first recurring subscription wasn't cancelled in Authorize.net (though maybe you just haven't gotten to this yet, since you said you still had to do cancellation processing).

**Comment by pippinsplugins** [comment] 2017-01-23 18:47
@nosegraze I've just pushed a fix for the 7 day error. It now shows a message on the registration page if attempting to register for a level that uses less than a 7 day renewal period.

**Comment by pippinsplugins** [comment] 2017-01-23 19:16
Member cancellation handling is in!

I also fixed the fatal error message @nosegraze encountered above.

Todo still:

- Payment logging
- Card updates

**Comment by pippinsplugins** [comment] 2017-01-23 19:30
Billing card update processing is done.

**Comment by pippinsplugins** [comment] 2017-01-23 19:30
@nosegraze 
>>> When I look in Authorize.net, all my test payments are marked as "pending transactions" or "scheduled payments". Is that expected?

That is normal for Authorize.net.

**Comment by pippinsplugins** [comment] 2017-01-23 19:34
Account upgrades should work properly now.

**Comment by pippinsplugins** [comment] 2017-01-23 19:42
@mindctrl @nosegraze ok this is ready for more thorough testing.

Note: for payments to be recorded, you need to have `Silent Post` configured in Authorize.net. Go to Account > Silent Post URL.

It needs to be set to `site.com/?listener=authnet`.

You will also need to set the MD5 Hash key. It's set in Account > MD5 Hash.

**Comment by pippinsplugins** [comment] 2017-01-23 19:43
Also note: I'm not certain I've _ever_ gotten silent post processing to work in Authorize.net sandbox. Seems they don't send them for sandbox accounts.

**Comment by nosegraze** [comment] 2017-01-24 13:19
To test:

- [ ] Non-recurring payment
- [ ] Recurring payment
- [ ] Payment with discount code
- [ ] Upgrading subscription
- [ ] User cancellation
- [ ] Update card details

@pippinsplugins So do I need to sign up for a live account then for silent post?

**Comment by nosegraze** [comment] 2017-01-24 13:30
`$payments` was still undefined so I fixed that here: https://github.com/restrictcontentpro/restrict-content-pro/pull/886/commits/03494fa98a9c07361991b73a0a037407e34ad8ec

**Comment by nosegraze** [comment] 2017-01-24 13:48
The zip code isn't updated in Authorize.net when updating billing information. (Everything else works okay though.)

**Comment by pippinsplugins** [comment] 2017-01-24 14:20
Thanks for catching the variable!

I'll need to get the zip code added.

For testing the  silent post . . . live sites are hard to get and not really worth it in my opinion. I would, instead, use [Postman](https://www.getpostman.com/) to simulate a silent post. You'll need to disable the MD5 hash validation to do it though.

**Comment by nosegraze** [comment] 2017-01-24 14:21
Okay I tested everything else in my list without silent post (and thus without payment records being added) but I'll setup Postman and have another go just to check that.

**Comment by pippinsplugins** [comment] 2017-01-24 14:23
Let me know if you need any guidance on how to simulate a post.

**Comment by nosegraze** [comment] 2017-01-24 15:11
Had a go with Postman and it seems to be working well. One thing: the subscription key wasn't showing up so I made a small tweak: https://github.com/restrictcontentpro/restrict-content-pro/pull/886/commits/5ba5ea7fed9ef87c7fc17447611659a2771e8bd6

**Comment by nosegraze** [comment] 2017-01-24 15:26
The webhook is used even for single payments, correct? If so, two things:

1. Should this: `$member->renew( true );` actually be this: `$member->renew( $member->is_recurring() );` ?

2. I think the expiration date could get set twice, so people get double the time they should get. In `process_signup()` the expiration date is set via `$member->set_expiration_date( $member->calculate_expiration() );` . Then when `process_webhooks()` kicks in, the expiration date would be updated a second time via `$member->renew( true );`. Here's a log for a brand new user when making a payment for a 1 week subscription, then triggering the post request:

```

January 24, 2017 15:22:42 - Member's status changed from  to pending

January 24, 2017 15:22:43 - Member's expiration changed from  to 2017-01-31 23:59:59

January 24, 2017 15:22:43 - Member's status changed from pending to active

January 24, 2017 15:22:43 - Subscription started in Authorize.net

January 24, 2017 15:23:37 - Member's expiration changed from 2017-01-31 23:59:59 to 2017-02-07 23:59:59

January 24, 2017 15:23:38 - Subscription processed in Authorize.net
```

**Comment by pippinsplugins** [comment] 2017-01-24 16:09
1. Good catch, yes I think that's right.

2. To resolve that, we should do what we do in Stripe and detect when the webhook is for the first payment in a subscription and only update the expiration if it's _not_ the first payment.

**Comment by pippinsplugins** [comment] 2017-01-24 22:32
1. Resolved.

**Comment by nosegraze** [comment] 2017-01-26 12:40
Added separate fields for live and test credentials: https://github.com/restrictcontentpro/restrict-content-pro/pull/886/commits/6794a12fe1199b7a59cc8abd69db956419638308

**Comment by nosegraze** [comment] 2017-01-26 12:50
Would this fix #2 from above? https://github.com/restrictcontentpro/restrict-content-pro/pull/886/commits/919350d5a17ecc323e817ba4fb1e277a8411a99d

**Comment by pippinsplugins** [comment] 2017-01-26 15:13
@nosegraze Yes! That should do it! I didn't realize Authorize.net sent that!

**Comment by pippinsplugins** [comment] 2017-01-26 15:15
I believe that wraps this up, excluding free trial support. So once #335 is finished, we can update this with trial support.

**Comment by nosegraze** [comment] 2017-01-27 16:02
Need to tweak something with cancelling subscriptions. `rcp_can_member_cancel()` fails in sandbox mode if the live API details aren't filled out but the test ones are.

**Comment by nosegraze** [comment] 2017-01-27 16:11
Should be all good now!

**Comment by pippinsplugins** [comment] 2017-01-27 16:27
Let's merge once tests complete.

**Comment by mindctrl** [comment] 2017-01-27 18:45
Merged. 🎉

**Closed by mindctrl** 2017-01-27 18:45 UTC
Labels: enhancement, has PR, needs testing
