### ISSUE TITLE
Stripe coupons duration set as forever

### ISSUE THREAD

**Issue by luke-au** [restrictcontentpro/restrict-content-pro#1297] opened 2017-06-29 08:19 UTC
I've found in a test environment when adding these Discount codes Stripe would get the data as `json 
"duration": "forever"
` that seems wrong doesn't it?

Name | Description | Code | Subscription | Amount | Type | Status | Uses | Uses Left | Expiration
------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
1 YEAR FREE | One free year of subscription. | 1yearfree | All Levels | $35.00 | Flat | active | 1/40 | yes | 2018-06-30
2017 First year free | 2017 First year free membership | free17 | All Levels | $35.00 | Flat | active | 0 | yes | 2018-06-01

### coupon.created

```json
{
  "object": {
    "id": "1yearfree",
    "object": "coupon",
    "amount_off": 3500,
    "created": 1498717337,
    "currency": "aud",
    "duration": "forever",
    "duration_in_months": null,
    "livemode": false,
    "max_redemptions": null,
    "metadata": {
    },
    "percent_off": null,
    "redeem_by": null,
    "times_redeemed": 0,
    "valid": true
  }
}
```
## POST /v1/coupons
**Request POST body**
```json
{
  "amount_off": "3500",
  "duration": "forever",
  "id": "1yearfree",
  "currency": "aud"
}
```

**Response body**
```json
{
  "id": "1yearfree",
  "object": "coupon",
  "amount_off": 3500,
  "created": 1498716114,
  "currency": "aud",
  "duration": "forever",
  "duration_in_months": null,
  "livemode": false,
  "max_redemptions": null,
  "metadata": {
  },
  "percent_off": null,
  "redeem_by": null,
  "times_redeemed": 0,
  "valid": true
}
```
---
### coupon.created

```json
{
  "object": {
    "id": "free17",
    "object": "coupon",
    "amount_off": 3500,
    "created": 1498718832,
    "currency": "aud",
    "duration": "forever",
    "duration_in_months": null,
    "livemode": false,
    "max_redemptions": null,
    "metadata": {
    },
    "percent_off": null,
    "redeem_by": null,
    "times_redeemed": 0,
    "valid": true
  }
}
```

## POST /v1/coupons
**Request POST body**
```json
{
  "amount_off": "3500",
  "duration": "forever",
  "id": "free17",
  "currency": "aud"
}
```

**Response body**
```json
{
  "id": "free17",
  "object": "coupon",
  "amount_off": 3500,
  "created": 1498718832,
  "currency": "aud",
  "duration": "forever",
  "duration_in_months": null,
  "livemode": false,
  "max_redemptions": null,
  "metadata": {
  },
  "percent_off": null,
  "redeem_by": null,
  "times_redeemed": 0,
  "valid": true
}
```

**Comment by nosegraze** [comment] 2017-06-29 12:05
We validate the coupons on RCP's end before they're applied to a purchase. So even though the Stripe coupon may last forever, that doesn't mean it can be added via registration forever. :)

**Comment by luke-au** [comment] 2017-06-29 12:13
Ok I see. But I did notice this sees a problem as far as manually assigning a subscriptions and coupon directly on Stripe itself as it's marked as forever.

**Comment by nosegraze** [comment] 2017-06-30 12:19
To clarify, assuming you have one-time discounts _disabled_, RCP discount codes are given to users for the entirety of their subscription. The expiration setting in RCP tells you the last date the coupon is allowed to be _applied_ to a new subscription. But users who already have the discount will continue to use it forever or until their subscription is cancelled. This is intended behaviour for RCP.

If you're wanting different behaviour when manually assigning a subscription/coupon in Stripe then you may want to create a different coupon.

**Comment by mindctrl** [comment] 2017-06-30 14:14
Our implementation doesn't jive up with Stripe's intended functionality. They say this about duration:

> One of forever, once, and repeating. Describes how long a customer who applies this coupon will get the discount.

Having said that, I don't think we can really change this to match Stripe's intent since we're already this deep in and it would cause disparity between our Stripe implementation and other gateways. Not to mention we created the "one time discounts" feature, and I'd hate to think what it would look like supporting one-time, forever, and specific duration discounts.

Thoughts?

**Comment by nosegraze** [comment] 2017-06-30 14:24
I know a few people who are interested in discounts that can recur x of times (which seems to be similar to Stripe's internal behaviour, but specifying a number rather than end date), but I don't think we should update our Stripe coupons to try to match that. **If** we do it, I think it should be something we do on our end that can then be used across all gateways.

**Comment by nosegraze** [comment] 2018-04-17 12:59
Closing this since it's working as intended, even if it's a bit wonky with Stripe's expectations. If we end up wanting to change how discounts work or add the "recur x times" feature mentioned above we can open a new issue.

**Closed by nosegraze** 2018-04-17 12:59 UTC
Labels: gateway
