### ISSUE TITLE
Free trial options

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#335] opened 2016-01-29 17:19 UTC
Could be nice to offer a two week trial.

> I would like to offer a two week free trial to certain users. I am going to setup an exit popup similar to the affiliatewp exit popup but instead of offering a discounted percent I would like to offer a two week free trial.

**Comment by mindctrl** [comment] 2016-04-08 15:44
We've been asked a number of times how to do something like this:

$9.99/month recurring with a 7 day free trial, without having to pay anything on the first day and without having to go through registration twice to jump from a free sub to a paid one.

In other words, delay billing until day 8 and then do the charge - if the member doesn't cancel beforehand.

Some folks are ok with doing a negative signup fee, but this doesn't delay the billing to offer a true free trial period.

**Comment by pippinsplugins** [comment] 2016-04-08 16:08
Let's make it happen.

**Comment by mrpritchett** [comment] 2016-06-13 12:46
I'd also like to add that it would be a huge deal to be able to add free trials with no payment info up front? So the user would be forced to pay for their plan (provide CC info, etc) X days after signing up for free trial. Would love to help out with coding this.

**Comment by pippinsplugins** [comment] 2016-06-13 13:07
@mrpritchett That's one of the elements we hope to cover in this :)

**Comment by derickbailey** [comment] 2016-07-27 14:23
can I also request paid trials, not just free trials?

i offer a 1-year paid membership for my site, and I would like to do something like "30 days for $30" as my trial membership

**Comment by mindctrl** [comment] 2016-07-27 15:53
I think paid trials would fall under per-level auto-renew settings. https://github.com/restrictcontentpro/restrict-content-pro/issues/548

**Comment by derickbailey** [comment] 2016-07-27 17:55
@mindctrl that would be a good start, but I don't think it would be a great long-term solution.

When I see "paid trial", my expectation is to have an automatic continuation after the trial period is over. In other words, "pay $30 now. in 30 days, you'll automatically be billed the full $349 for the next year of membership".

The ability to set a plan as not auto-renewing, at the plan level, would make it easy to give people a "trial" plan for 30 days. But there is no automatic upgrade / continuation of the membership, after that. 

Having to switch plans would require some action on the user's part (including re-entering their credit card information, i think... based on the testing i've done for upgrading, anyways).

Unless #548 can be coupled with another feature to automatically switch plans when one expires. But that seems like it would be a strange thing to do, just to make paid trial accounts work.

I don't necessarily know what the solution looks like, but the feature that I would prefer is to automatically bill for the full-term plan, after the paid trial is done.

**Comment by mindctrl** [comment] 2016-07-27 17:57
@derickbailey ok I see what you're saying now. Thanks for the details. We'll give this some consideration.

**Comment by pippinsplugins** [comment] 2016-10-26 00:12
Request: https://secure.helpscout.net/conversation/268745742/45342/?folderId=841776

**Comment by kevinlampron916** [comment] 2016-10-27 03:17
Hey guys! Just wanted to chime in and say thank you Pippin and the crew for making awesome plugins!

I would also like to say that a Free Trial option would be absolutely huge! I know just because I am one looking for this option.

I really hope you all put this one at the top of your lists. I have 3 of the top Membership plugins.
RCP, MemberPress & Woo Memberships.

I would really like to use RCP. Anyway hope you all have an amazing day!

**Comment by nosegraze** [comment] 2016-11-23 21:15
I've gotten a few requests for this too, including a similar type of "paid trial" @derickbailey mentioned. Example:

Pay $20 for 40 days access to content.
At the end of 40 days, be transitioned into the same membership, but billed yearly.

So the first $20 access is like a cheaper preview of the content, but the real plan is the yearly one.

**Comment by helsinglee** [comment] 2016-11-30 02:26
@michaelbeil Could U add drop-down list option for the paid items?  If I had more than 8 items to sell, it will not easy to select it. Other, how to sort the payment methods?

**Comment by mindctrl** [comment] 2017-01-06 23:32
If we do paid trials, we need to consider how this might affect other add-ons and events that tie into payment creation. A couple examples off the top of my head are the EDD Wallet integration, EDD Member Downloads, EDD FES Vendor Limits, Limited Quantity Available, and the WP Job Manager add-on.

**Comment by mindctrl** [comment] 2017-01-25 15:12
@pippinsplugins @nosegraze this is ready for a first round of tests.

I've been unable to reliably test PayPal Pro due to sandbox account issues.

**Comment by mindctrl** [comment] 2017-01-25 15:15
You'll probably need to deactivate/activate to trigger the database upgrade for the new trial columns, because the version was bumped to 2.7 earlier in the dev cycle for something else.

**Comment by pippinsplugins** [comment] 2017-01-25 15:28
Excellent! I'll start testing shortly.

**Comment by pippinsplugins** [comment] 2017-01-25 16:07
Quick thing I noticed. I have a 5 day trial set up but it shows as `Free trial - 5 day` on registration. Should be `days`, not `day`.
![screen shot 2017-01-25 at 10 06 37 am](https://cloud.githubusercontent.com/assets/1034109/22298413/1045a3fa-e2e6-11e6-970d-e1a24c16cdff.png)

**Comment by pippinsplugins** [comment] 2017-01-25 16:08
Also the `Auto Renew` box needs to automatically go away when a free trial is selected.

**Comment by mindctrl** [comment] 2017-01-25 16:08
Auto Renew box should be checked and hidden when selecting a free trial, if the selected gateway supports it. #658 related.

**Comment by mindctrl** [comment] 2017-01-25 16:09
Checklist:
- [ ] Run free trial text through rcp_filter_duration_unit()

**Comment by pippinsplugins** [comment] 2017-01-25 16:12
@mindctrl I'm testing with PayPal Standard and it was not hidden.

Also, I just got this error when going to PayPal:

>>>The link you have used to enter the PayPal system is invalid. Please review the link and try again.

These are the args passed to PayPal:

Array
(
    [business] => 
    [email] => pippin@pippinsplugins.com
    [item_number] => c4b3aac46c4997f4ca1f1b74af0ec223
    [item_name] => Bronze
    [no_shipping] => 1
    [shipping] => 0
    [no_note] => 1
    [currency_code] => USD
    [charset] => UTF-8
    [custom] => 1
    [rm] => 2
    [return] => https://edd.com/rcp/register/welcome/
    [cancel_return] => https://edd.com/rcp
    [notify_url] => https://edd.com/rcp/index.php?listener=IPN
    [cbt] => Restrict Content Pro Test Site
    [tax] => 0
    [page_style] => 
    [bn] => EasyDigitalDownloads_SP
    [cmd] => _xclick-subscriptions
    [src] => 1
    [sra] => 1
    [a3] => 12.5
    [p3] => 1
    [t3] => M
    [a1] => 0
    [p1] => 5
    [t1] => D
)

**Comment by pippinsplugins** [comment] 2017-01-25 16:21
I keep getting this error in Stripe:

Message: Customer cus_9ztDi8jMsT0Jte does not have a subscription with ID sub_9sSKMbisGV3nAE

I've deleted the profile ID and customer ID . . .  .not sure if it's related.

**Comment by pippinsplugins** [comment] 2017-01-25 16:27
Ignore that Stripe error. Fixed it.

Stripe is working great.

**Comment by pippinsplugins** [comment] 2017-01-25 16:30
Looks like we need to block customers from re-using free trials. I was able to subscribe to a free trial twice.

1. Subscribe to free trial
2. Upgrade to paid plan without trial
3. Upgrade to free trial

Step 3 should not have been permitted.

**Comment by mindctrl** [comment] 2017-01-25 16:34
@pippinsplugins I can't replicate the issue with PayPal Standard. Did you happen to be upgrading? I'm wondering if that's the calculation bug in #668.

**Comment by pippinsplugins** [comment] 2017-01-25 16:43
@mindctrl I was upgrading but not with a pro-rated amount.

**Comment by mindctrl** [comment] 2017-01-25 16:55
Updated PR to not show free trials to members that have already used one.

**Comment by pippinsplugins** [comment] 2017-01-25 16:55
Looks good there.

**Comment by mindctrl** [comment] 2017-01-25 17:05
Still unable to replicate PayPal Standard issue. I tried this:

- subscribed to a paid level that does not have a trial
- upgraded to a different level with a free trial
- upgraded to a different level without a trial

All worked as expected.

**Comment by nosegraze** [comment] 2017-01-26 15:32
IMO this should be revisited: https://github.com/restrictcontentpro/restrict-content-pro/commit/56bde243c13967c022fe53f989036913cfcc7810

- I've used up a free trial from Subscription Level A (from a separate free trial plan - the kind we had before).
- I now want to upgrade to a paid plan on Subscription Level B, which also happens to have a free trial added.
- But that entire plan is hidden from the page, since it contains a free trial so I can't upgrade to it at all.

I think the plan should still show up in the list, the free trial part of it just shouldn't be offered and they should pay straight away.

**Comment by pippinsplugins** [comment] 2017-01-26 15:36
>>>I think the plan should still show up in the list, the free trial part of it just shouldn't be offered and they should pay straight away.

I agree with that, and that's the same thing way we decided to handle it in EDD Recurring Payments, so consistency for the win.

**Comment by nosegraze** [comment] 2017-01-26 15:48
Didn't have any problems with PayPal Standard. Looks good for me.

Stripe Checkout was a bit scary, though it works fine. The modal says, "Register - $30", which makes it look like you're paying now, even though you're not.

**Comment by pippinsplugins** [comment] 2017-01-26 16:02
We should adjust the amount shown in Stripe Checkout. Perhaps even remove it entirely when signing up for a trial.

**Comment by mindctrl** [comment] 2017-01-26 19:18
@nosegraze @pippinsplugins Updated PR to show levels with free trials per https://github.com/restrictcontentpro/restrict-content-pro/issues/335#issuecomment-275418393.

Also updated to not show price on Stripe Checkout button if a trial is selected.

Alipay requires the amount, so I just forced it in that case.

**Comment by nosegraze** [comment] 2017-01-26 19:21
Will take a look in a bit. :)

FYI I haven't been able to test with PayPal Pro yet due to SoftDescriptor crap.

**Comment by nosegraze** [comment] 2017-01-26 19:51
I'm happy with the above changes!

**Comment by mindctrl** [comment] 2017-01-26 19:55
Yay!

I just noticed something that I haven't seen before, and I haven't had a chance to dig into it yet. Not sure if this is new or existing.

Some webhooks are getting this response from RCP:
```
PHP exception: No API key provided.  (HINT: set your API key using "Stripe::setApiKey(<API-KEY>)".  You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
```

**Comment by mindctrl** [comment] 2017-01-26 20:25
re: https://github.com/restrictcontentpro/restrict-content-pro/issues/335#issuecomment-275495180. unrelated to this, happening in 2.6.x too.

**Comment by mindctrl** [comment] 2017-01-26 20:58
@pippinsplugins one thing we lack here is confirmed tests with PayPal Pro. Can you do that?

**Comment by pippinsplugins** [comment] 2017-01-26 21:00
@mindctrl will try and test that shortly.

**Comment by pippinsplugins** [comment] 2017-01-26 21:14
@mindctrl I see the `rcp_has_used_trial()` logic repeated in each gateway.

Can we please move that to the registration processing to reduce code duplication? gateways shouldn't be performing any of that logic, they should simply be handling the data handed to them from the registration processing.

**Comment by pippinsplugins** [comment] 2017-01-26 21:20
PayPal Pro appeared to work fine!

**Comment by pippinsplugins** [comment] 2017-01-26 21:24
Yep, confirmed. PayPal Pro worked properly!

**Comment by mindctrl** [comment] 2017-01-26 22:00
> I see the rcp_has_used_trial() logic repeated in each gateway.

Derp, good catch. Will update.

**Comment by mindctrl** [comment] 2017-01-26 23:47
@pippinsplugins updated the trial check logic.

For the record, the key issue mentioned [here](https://github.com/restrictcontentpro/restrict-content-pro/issues/335#issuecomment-275495180) was a facepalm moment. I somehow had disabled sandbox mode accidentally.

**Comment by pippinsplugins** [comment] 2017-01-27 15:00
This is looking good!

Anything else or ready to merge?

**Comment by mindctrl** [comment] 2017-01-27 15:04
I think we're all good here!

**Comment by mindctrl** [comment] 2017-01-27 15:04
Oh wait, I need to add phpdoc to `is_trial()`

**Comment by pippinsplugins** [comment] 2017-01-27 15:05
:+1: Do that then go ahead and merge! Once this is merged, we can finalize the auth.net updates.

**Closed** 2017-01-27 15:19 UTC
Labels: enhancement
