### ISSUE TITLE
.ui-tooltip styles clashing with Gravity Form's .ui-tooltip styles

### ISSUE THREAD

**Issue by m-e-h** [restrictcontentpro/restrict-content-pro#1238] opened 2017-05-12 21:38 UTC
and making for some pretty nasty and barely legible tips.

![ui-tooltip](https://cloud.githubusercontent.com/assets/3585901/26017706/f7f423ce-3738-11e7-83a6-a1078434d597.png)

`gravityforms/css/tooltip.css`

**Comment by mindctrl** [comment] 2017-05-12 21:49
That's a gnarly text shadow. Thanks for the heads up. We'll get this updated.

**Comment by m-e-h** [comment] 2017-05-12 21:56
Ha! I first saw that and was like, surely nobody thinks that text shadow and border are a good idea.

**Comment by pippinsplugins** [comment] 2017-05-25 14:19
Same problem was in EDD https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5115

**Comment by nosegraze** [comment] 2017-05-26 12:40
Went to make a PR, but I actually can't reproduce this. I could guess at what CSS to add, but if you can reproduce this @mindctrl want to do the PR instead?

**Comment by mindctrl** [comment] 2017-05-26 15:01
@nosegraze I'm not seeing the issue either. I just checked it on the EDD site and it looks fine. I don't see the GF CSS loading there either.

![image](https://cloud.githubusercontent.com/assets/1254870/26500062/a2a11524-4202-11e7-9f1a-ecdf7abec7c4.png)

@m-e-h are you on the latest version of GF?

**Comment by m-e-h** [comment] 2017-05-26 16:05
I just checked again and Gravity Forms does not load its scripts on that page, which it would have no reason to.
However it seems the Gravity View plugin does load the GF scripts on the page.

I'll create an issue on the GV repo. Not sure that this is something RCP should even worry about.

**Comment by mindctrl** [comment] 2017-05-26 17:08
Thanks for the update! I'll close this out. If you see via the other issue that we need to make an adjustment here, feel free to reopen this.

**Closed by mindctrl** 2017-05-26 17:08 UTC
Labels: bug
