### ISSUE TITLE
BUG: PayPal Express: RCP 1.8.0

### ISSUE THREAD

**Issue by lordspace** [restrictcontentpro/restrict-content-pro#1083] opened 2017-03-12 12:03 UTC
When the user returns from paypal express (after accepting the paypal terms) some notices are shown.

 ! ) Notice: Undefined index: FIRSTNAME in /var/www/vhosts/staging.go359.com/htdocs/wp-content/plugins/restrict-content-pro-2.8/templates/paypal-express-confirm.php on line 19

The same notice is shown for these fields.
LASTNAME
PAYERSTATUS 
EMAIL 
DESC 
PAYMENTREQUEST_0_AMT 

[staging.go359_rcp_paypal_express.pdf](https://github.com/restrictcontentpro/restrict-content-pro/files/836482/staging.go359_rcp_paypal_express.pdf)

After click on the confirm button this error is shown.

Notice: Undefined index: AMT in /var/www/vhosts/staging.go359.com/htdocs/wp-content/plugins/restrict-content-pro-2.8/includes/gateways/class-rcp-payment-gateway-paypal-express.php on line 200
Call Stack
#	Time	Memory	Function	Location
1	0.0013	285128	{main}( )	../index.php:0
2	0.0013	285592	require( '/var/www/vhosts/staging.go359.com/htdocs/wp-blog-header.php' )	../index.php:17
3	0.9350	18720648	require_once( '/var/www/vhosts/staging.go359.com/htdocs/wp-includes/template-loader.php' )	../wp-blog-header.php:19
4	0.9350	18720696	do_action( )	../template-loader.php:12
5	0.9350	18721368	WP_Hook->do_action( )	../plugin.php:453
6	0.9350	18721464	WP_Hook->apply_filters( )	../class-wp-hook.php:323
7	0.9351	18723480	call_user_func_array ( )	../class-wp-hook.php:298
8	0.9351	18723912	rcp_process_gateway_confirmations( )	../class-wp-hook.php:298
9	0.9418	18737048	RCP_Payment_Gateway_PayPal_Express->process_confirmation( )	../gateway-functions.php:194

( ! ) Notice: Undefined index: CURRENCYCODE in /var/www/vhosts/staging.go359.com/htdocs/wp-content/plugins/restrict-content-pro-2.8/includes/gateways/class-rcp-payment-gateway-paypal-express.php on line 202
Call Stack
#	Time	Memory	Function	Location
1	0.0013	285128	{main}( )	../index.php:0
2	0.0013	285592	require( '/var/www/vhosts/staging.go359.com/htdocs/wp-blog-header.php' )	../index.php:17
3	0.9350	18720648	require_once( '/var/www/vhosts/staging.go359.com/htdocs/wp-includes/template-loader.php' )	../wp-blog-header.php:19
4	0.9350	18720696	do_action( )	../template-loader.php:12
5	0.9350	18721368	WP_Hook->do_action( )	../plugin.php:453
6	0.9350	18721464	WP_Hook->apply_filters( )	../class-wp-hook.php:323
7	0.9351	18723480	call_user_func_array ( )	../class-wp-hook.php:298
8	0.9351	18723912	rcp_process_gateway_confirmations( )	../class-wp-hook.php:298
9	0.9418	18737048	RCP_Payment_Gateway_PayPal_Express->process_confirmation( )	../gateway-functions.php:194

PayPal payment processing failed.

Error message: Bill amount must be greater than 0

Error code: 11519

**Comment by lordspace** [comment] 2017-03-12 12:29
Plans have their price set.

**Comment by nosegraze** [comment] 2017-03-14 15:34
Just tested a PayPal Express registration and didn't get any errors. Someone else want to give it a try?

**Comment by pippinsplugins** [comment] 2017-03-14 18:07
That stack makes it look like the `$rcp_checkout_details` variable didn't get set up at all.

@lordspace is this on a blank site or do you have customizations active for RCP?

**Comment by lordspace** [comment] 2017-03-14 18:24
It's a staging site that I've cloned from an existing site. It's set up as multisite (subsites as folders). The plugin is network activated. This happens on the main site. 
No customizations to the code (I've downloaded the tag 2.8 from github).
I have some hooks added but  they are related to plan changes.

**Comment by mindctrl** [comment] 2017-03-14 18:38
I'm unable to replicate this either.

@lordspace can you post screenshot of your subscription level configuration? Also it would be great to see a system info file.

**Comment by lordspace** [comment] 2017-03-14 22:06
I've switched the WP's language to English and created an admin account for you.
WP should have sent a confirmation email to the support email.
In case you want to login and take a look.
https://staging.go359.com/wp-admin/


Here's the info.

```
### Begin System Info ###

-- Site Info

Site URL:                 https://staging.go359.com
Home URL:                 http://staging.go359.com
Multisite:                Yes

-- WordPress Configuration

Version:                  4.7.3
Language:                 en_US
Permalink Structure:      /blog/%year%/%monthnum%/%day%/%postname%/
Active Theme:             Startuply WP Child Theme 2.5.2
Show On Front:            page
Page On Front:            Начало (#11)
Page For Posts:           Блог (#66)
ABSPATH:                  /var/www/vhosts/staging.go359.com/htdocs/
Table Prefix:             Length: 3   Status: Acceptable
WP_DEBUG:                 Enabled
Memory Limit:             256M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, acf-disabled

-- RCP Configuration

Version:                          2.8
License Key:                      Not set
Auto Renew:                       Always auto renew
Currency:                         EUR
Currency Position:                before
Sandbox Mode:                     True

-- RCP Page Configuration

Registration Page:                http://staging.go359.com/%d0%b0%d0%b1%d0%be%d0%bd%d0%b8%d1%80%d0%b0%d0%b9-%d1%81%d0%b5/
Success Page:                     http://staging.go359.com/%d0%b0%d0%b1%d0%be%d0%bd%d0%b8%d1%80%d0%b0%d0%b9-%d1%81%d0%b5/welcome/
Account Page:                     http://staging.go359.com/%d0%b0%d0%b1%d0%be%d0%bd%d0%b8%d1%80%d0%b0%d0%b9-%d1%81%d0%b5/your-membership/
Edit Profile Page:                http://staging.go359.com/%d0%b0%d0%b1%d0%be%d0%bd%d0%b8%d1%80%d0%b0%d0%b9-%d1%81%d0%b5/edit-your-profile/
Update Billing Card Page:         http://staging.go359.com/%d0%b0%d0%b1%d0%be%d0%bd%d0%b8%d1%80%d0%b0%d0%b9-%d1%81%d0%b5/update-billing-card/

-- RCP Gateway Configuration

Enabled Gateways:         PayPal (paypal)

-- RCP Misc Settings

Hide Premium Posts:               False
Redirect Page:                    http://staging.go359.com/app/
Redirect Default Login URL        False
Login Page:                       http://staging.go359.com/app/
Prevent Account Sharing:          False
Email IPN Reports:                False
Disable Form CSS:                 False
Enable reCaptcha:                 False
reCaptcha Site Key:               Unset
reCaptcha Secret Key:             Unset

-- Must-Use Plugins

dbg.php: 
sandbox.php: 

-- WordPress Active Plugins

Arconix FAQ: 1.6.1
Contact Form 7: 4.7
Contact Form DB: 2.10.28
Duplicator: 1.1.34
DW FitVids: 1.4
Free & Simple Contact Form Plugin - PirateForms: 1.2.0
Go359 Core: 1.0.0
Go359 Extension: Branding: 1.0.0
Go359 Extension: Control Panel: 1.0.0
Google Analytics Dashboard for WP: 4.9.6.2
WPBakery Visual Composer: 4.11.2.1 (needs update - 5.0.1)
WP Super Cache: 1.4.9
Yoast SEO: 4.4

-- WordPress Inactive Plugins

Core Control: 1.2.1
External Links: 6.7
Go359 Koleda: 1.0.0
Google Captcha (reCAPTCHA) by BestWebSoft: 1.27
Orbisius Simple Notice: 1.0.9
Orbisius Simple Shortlink: 1.0.3
Restrict Content Pro: 2.8
SyntaxHighlighter Evolved: 3.2.1
Under Construction: 1.18
WP Lightbox 2: 3.0.6.2
WP Notes Remover: 1.0.6

-- Network Active Plugins

Go359 Core: 1.0.0
Arconix FAQ: 1.6.1
Contact Form DB: 2.10.28
Contact Form 7: 4.7
Core Control: 1.2.1
DW FitVids: 1.4
Go359 Koleda: 1.0.0
Google Captcha (reCAPTCHA) by BestWebSoft: 1.27
Orbisius Simple Notice: 1.0.9
Orbisius Simple Shortlink: 1.0.3
Restrict Content Pro: 2.8
External Links: 6.7
SyntaxHighlighter Evolved: 3.2.1
Yoast SEO: 4.4
WP Lightbox 2: 3.0.6.2
WP Notes Remover: 1.0.6

-- Webserver Configuration

PHP Version:              5.5.9-1ubuntu4.21
MySQL Version:            5.5.54
Webserver Info:           Apache

-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          50M
Post Max Size:            256M
Upload Max Filesize:      50M
Time Limit:               30
Max Input Vars:           6000
Display Errors:           On (1)

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

### End System Info ###
```

**Comment by nosegraze** [comment] 2017-03-21 12:22
@lordspace For both this and #1084 can you please contact us through our support page here: https://restrictcontentpro.com/support/

It looks like these issues may be specific to your setup so we'd like to discuss this more through our support channel until we can verify if they're bugs with RCP or something with your setup. Hopefully we can get it all sorted out!

**Comment by nosegraze** [comment] 2017-03-29 11:56
Closing this for now. Will re-open if we find an error we can reproduce.

**Closed by nosegraze** 2017-03-29 11:56 UTC
Labels: bug
