### ISSUE TITLE
Payment Dates in RCP are five hours ahead of payment processor

### ISSUE THREAD

**Issue by carter2422** [restrictcontentpro/restrict-content-pro#298] opened 2015-12-01 16:43 UTC
We thought this was fixed a while back but it's still an issue. 

When payments are entered into RCP they are pushed five hours into the future, causing confusing for users and admins.

For example, a user paid via Stripe on `2015/10/31 19:49:04`, yet in RCP the payment is noted as `2015-11-01 12:49:05`

**Comment by ramiy** [comment] 2016-01-23 02:15
Had the same problem with PayPal - 8 hours difference.

The time difference caused by the way the plugin handles payment dates. PayPal has it's own TimeZone settings, and RCP uses WordPress TimeZone settings.

I fixed that by matching PayPal and WordPress timezones. But I think I should be handled by the plugin. Maybe to add a checkbox to the settings page to allow the plugin to use paypal dates, not wordpress dates?

**Comment by pippinsplugins** [comment] 2016-01-24 06:35
I think I can force them to match.

**Comment by tannerm** [comment] 2016-03-12 00:31
@pippinsplugins I have not been able to test this very well with PayPal, but the issue is resolved with Stripe and I'm pretty sure PayPal is good too.

**Comment by pippinsplugins** [comment] 2016-03-13 01:22
:+1:

**Closed** 2016-03-18 16:17 UTC
Labels: bug
