### ISSUE TITLE
Stripe Checkout Doesn't Register the Payments Date

### ISSUE THREAD

**Issue by RuiSantosdotme** [restrictcontentpro/restrict-content-pro#433] opened 2016-04-06 18:02 UTC
RCP 2.5 with Stripe checkout is not registering the dates properly in the Restrict > Payments tab:
![stripeproblem](https://cloud.githubusercontent.com/assets/6280520/14329998/3f6cea36-fc36-11e5-9af8-c62fa15ad668.JPG)

It's submitting a NULL value, so it stores the epoch time. 
I think the problem is on this line 402 or 406: https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/gateways/class-rcp-payment-gateway-stripe.php

Thanks

**Comment by RuiSantosdotme** [comment] 2016-04-06 18:03
These are real transactions from my customers that have the date messed up.

**Comment by pippinsplugins** [comment] 2016-04-06 18:07
I'm pretty sure it is `get_date_from_gmt( $payment_date->format( 'c' ) )`.

I'll confirm shortly and fix.

**Comment by mindctrl** [comment] 2016-04-06 18:35
@RuiSantosdotme please restore some of the information in the original post so there's a good log of what the issue is.

**Comment by pippinsplugins** [comment] 2016-04-06 19:21
I've processed numerous renewal payments through Stripe in the last two weeks and have not seen this happen.

@RuiSantosdotme What's the PHP version on your site?

**Comment by RuiSantosdotme** [comment] 2016-04-06 19:25
Here's the version
![php](https://cloud.githubusercontent.com/assets/6280520/14329907/b28ae56e-fc35-11e5-9cbf-5a86ffe0abbb.JPG)

**Comment by pippinsplugins** [comment] 2016-04-06 19:27
That should be fine.

Can you please send me the event data from Stripe for one of  the renewal payments?

**Comment by pippinsplugins** [comment] 2016-04-06 19:27
@RuiSantosdotme Also, as noted by @mindctrl above, please do not delete the description of the original issue. That does not help us resolve your problem at all.

**Comment by RuiSantosdotme** [comment] 2016-04-06 19:30
I don't have any renewals. These are brand new paymenbts, because I've launched the website 4 days ago...

**Comment by pippinsplugins** [comment] 2016-04-06 19:34
Doesn't change the fact: they're recorded in the same way. Can you please show me the event data for the webhooks? Also what is the timezone set to your in your Stripe account and WordPress?

**Comment by RuiSantosdotme** [comment] 2016-04-06 19:39
Is this what you need for the Stripe Event Data?
![payment](https://cloud.githubusercontent.com/assets/6280520/14330233/83d48426-fc37-11e5-86fa-ab33df362230.JPG)

**Comment by RuiSantosdotme** [comment] 2016-04-06 19:43
Stripe timezone: WET/WEST - Lisbon 
WordPress timezone: UTC+0

They don't match. Always something wrong with timezones...
They don't match...

**Comment by pippinsplugins** [comment] 2016-04-06 19:50
Set them so they match and the problem will almost certainly go away. They need to match.

**Comment by RuiSantosdotme** [comment] 2016-04-06 19:52
The daylight saving time was last week in Portugal. Portugal went from UTC+0 to UTC+1.

I'll make another purchase attempt in just a couple o minutes

**Comment by RuiSantosdotme** [comment] 2016-04-06 20:02
The timezones between stripe and wordpress match, but the error persists...

**Comment by pippinsplugins** [comment] 2016-04-06 20:08
What do you have them both set to now?

**Comment by RuiSantosdotme** [comment] 2016-04-06 20:15
Stripe:
![stripe_timezone](https://cloud.githubusercontent.com/assets/6280520/14331263/7a8897b8-fc3c-11e5-83f5-ee8724734a23.JPG)
WordPress:
![wordpress_timezone](https://cloud.githubusercontent.com/assets/6280520/14331274/83b42802-fc3c-11e5-8697-8f44e6e9be76.JPG)
Purchase Attempt:
![purchase attempt](https://cloud.githubusercontent.com/assets/6280520/14331286/9126e2ae-fc3c-11e5-9191-e530e735aa75.JPG)

RCP:
![rcp payments tab](https://cloud.githubusercontent.com/assets/6280520/14331288/980a7770-fc3c-11e5-8b7a-399789c107f0.JPG)

**Comment by mindctrl** [comment] 2016-04-06 20:59
@RuiSantosdotme thanks. Does it work right if you set both to UTC?

**Comment by RuiSantosdotme** [comment] 2016-04-06 21:11
@mindctrl both on UTC, but same problem...

**Comment by michaelbeil** [comment] 2016-04-07 06:59
We will be resting this further @RuiSantosdotme.

**Comment by pippinsplugins** [comment] 2016-04-07 14:15
Just received another report of this, though only with some payments: https://secure.helpscout.net/conversation/189655848/31658/?folderId=223654

**Comment by pippinsplugins** [comment] 2016-04-07 14:19
@mindctrl Can you please test this with https://github.com/restrictcontentpro/restrict-content-pro/pull/437?

**Comment by mindctrl** [comment] 2016-04-07 14:29
Tested with UTC+2, UTC+12, and UTC-4. All worked great.

**Comment by pippinsplugins** [comment] 2016-04-07 14:30
Merged.

**Closed by pippinsplugins** 2016-04-07 14:30 UTC
Labels: bug
