### ISSUE TITLE
"Member Payments" hover action link on the Member Payments page

### ISSUE THREAD

**Issue by luke-au** [restrictcontentpro/restrict-content-pro#1709] opened 2018-03-06 04:56 UTC
When hovering over a users member payment item on the "Member Payments" page there is an item action link to visit that page link again "Member Payments" despite filtering the payments to one user ID. 

![screen shot 2018-03-06 at 15 30 16](https://user-images.githubusercontent.com/23548658/37014321-f27f080e-2153-11e8-9df9-7778a025050b.png)

**Comment by tnorthcutt** [comment] 2018-04-23 02:05
@luke-au I don't think I understand the problem.

When I click the "Member Payments" link, it takes me to a page with all the payments by that one member. Is this not the intended behavior?

What happens when you click this link? What do you expect to happen?

**Comment by tnorthcutt** [comment] 2018-04-23 15:40
We should probably address this as part of https://github.com/restrictcontentpro/restrict-content-pro/issues/1794

**Comment by tnorthcutt** [comment] 2018-04-23 15:40
Closing; included in https://github.com/restrictcontentpro/restrict-content-pro/issues/1794 now

**Closed by tnorthcutt** 2018-04-23 15:40 UTC
Labels: bug
