### ISSUE TITLE
Card Update Form - blank page/no message

### ISSUE THREAD

**Issue by thomasfw** [restrictcontentpro/restrict-content-pro#317] opened 2016-01-11 16:01 UTC
The page containing `[rcp_update_card]` is blank when visited by a user without (as far as I can see) an active paid membership (e.g. free membership tier). Can we add a default message and/or hook here rather than showing a blank page?

And slightly related - was there any progress with displaying details of the current card on file #230?

**Comment by pippinsplugins** [comment] 2016-01-12 04:26
Can you show me a screenshot of the edit screen for a member that doesn't seee it?

**Comment by thomasfw** [comment] 2016-02-11 16:20
Sorry about the late response. I can't take any screenshots but this is easily replicated by signing up to a free membership tier and visiting the page containing the shortcode.

**Comment by mindctrl** [comment] 2016-02-11 21:51
Appears to be on purpose for now: https://github.com/restrictcontentpro/restrict-content-pro/blob/6ffc863c9ad20ef79a1dc32df690d30077d77878/includes/member-functions.php#L1228

If it stays that way maybe we can show a message instead.

**Comment by pippinsplugins** [comment] 2016-02-11 22:15
I'd prefer that we not show a message. No reason to show a message of `You can only update your card if X, Y, and Z are true`. Customer's don't need to know that there is a form if it doesn't apply to them.

**Comment by pippinsplugins** [comment] 2016-03-18 17:49
Duplicate of #230

**Closed by pippinsplugins** 2016-03-18 17:49 UTC
Labels: bug
