### ISSUE TITLE
Bundle Braintree into core

### ISSUE THREAD

**Issue by pippinsplugins** [restrictcontentpro/restrict-content-pro#142] opened 2015-04-03 17:04 UTC
Braintree should be put into core.

**Comment by vispthree** [comment] 2015-05-02 14:08
Need to beef up my resume and hone my coding skills so I've started wrapping my head around this plugin... all the better that success = promoting crypto-currencies and all the free education you offer.  Although, if this is too large of a project then I'll refocus my efforts.

**Comment by pippinsplugins** [comment] 2015-05-02 22:49
Let me know if you have any questions.

**Comment by mindctrl** [comment] 2017-02-23 15:44
@nosegraze @pippinsplugins PR submitted. Still needs a few things but I'd like to get some eyeballs and testing on it.

**Comment by pippinsplugins** [comment] 2017-02-23 15:54
@mindctrl left a couple of small notes.

Could we also detect if the old add-on is installed and auto deactivate / show a notice?

**Comment by mindctrl** [comment] 2017-02-23 17:26
Due to https://github.com/restrictcontentpro/restrict-content-pro/issues/670, we'll need to show a notice for people to update their webhooks in Braintree. Our old instructions just instructed people to add their `home_url()`.

We have a few options.

- Force deactivate the old plugin, show a notice, and have the user update the webhook. I really want to do this option as it's the cleanest code option, but you know people often ignore admin notices.
- Don't run this new code unless the old Braintree plugin is deactivated. Meh, this means most people stick with the old Braintree code.
- Add to the conditional in #670 to also check for the old Braintree pattern, or perhaps introduce a new filter there and tie into it to force run the webhook from inside the new Braintree if the proper `$_POST` vars are set. Kinda meh on this too, but I'd be ok with it over the second option.

@pippinsplugins @nosegraze thoughts or other ideas?

**Comment by mindctrl** [comment] 2017-02-23 17:32
Linked the wrong issue. Updated: https://github.com/restrictcontentpro/restrict-content-pro/issues/976

**Comment by nosegraze** [comment] 2017-02-23 17:40
I definitely like the first option best. But I suppose we could tack in #3 just for a small interim period?

**Comment by mindctrl** [comment] 2017-02-23 19:40
Pushed an update that adds a filter, a check for relevant `$_GET` / `$_POST` vars, and deactivates the old plugin.

**Comment by mindctrl** [comment] 2017-02-23 19:43
I need to add some checks for PHP version to ensure things don't run on pre-5.4.

**Comment by nosegraze** [comment] 2017-02-23 21:09
Will do some testing tomorrow. List:

- [ ] Regular one time payment.
- [ ] Regular recurring subscription.
- [ ] Recurring payment with discount.
- [ ] Single payment with discount.
- [ ] Recurring payment with signup fee.
- [ ] Single payment with signup fee.
- [ ] Recurring payment with free trial.
- [ ] One-time discount codes.

(If any of those aren't ready for testing, let me know.)

**Comment by mindctrl** [comment] 2017-02-24 07:04
This isn't quite ready to test yet, but it's getting late. I'll ping you when it's ready.

**Comment by pippinsplugins** [comment] 2017-02-24 15:35
Dropping a note so we don't forget: let's email all customers that have downloaded the plugin from pippinsplugins.com and let them know of the new version.

**Comment by mindctrl** [comment] 2017-02-27 18:19
When a free trial is cancelled before the first payment, there is no customer ID info sent in the webhook data. That's because Braintree stores the customer ID in the webhook inside the transaction object, and since there are no transactions there is no customer ID sent. We do get the subscription ID though.

I introduced a new helper function, `rcp_get_member_id_from_subscription_id()`, which gets the user ID from the processor subscription ID. It's a copy of `rcp_get_member_id_from_profile_id()` and just changes the meta key.

**Comment by pippinsplugins** [comment] 2017-02-27 19:02
:+1:

**Comment by mindctrl** [comment] 2017-02-27 19:03
re: signup fees.

Braintree has only one "amount" field when creating a subscription. They don't have "initial amount", or anything like that. They also do not have a customer balance concept like Stripe. That means when creating a subscription, if you include the signup fee in the amount, it applies to all payments.

However, they have something called ["add-ons"](https://articles.braintreepayments.com/guides/recurring-billing/add-ons-discounts), which can be used to add or subtract amounts from the subscription. The add-ons feature has an option for `numberOfBillingCycles`, which lets you apply the signup fee to the initial payment only. BUT, add-ons must be managed from the web control panel (like they require you do with plans).

That would mean, using add-ons for signup fees would require the user to create add-ons for signup fees, which they can then associate with the plan they already have to create to use recurring in Braintree.

From the looks of it, we do not support signup fees in the current Braintree plugin.

With all that in mind, I think we have a few options:
- use add-ons, document it, and maybe show some additional help text in the subscription add/edit screen when Braintree is active
- do a separate single charge for just the signup fee amount (have not tested this and don't like the idea really, but can be convinced otherwise)
- don't support signup fees (not really an option for a first class gateway in core)

Maybe there's another idea?

**Comment by pippinsplugins** [comment] 2017-02-27 19:04
I vote for option 2. It kind of sucks but that's how we had to do it in Recurring Payments for EDD and several gateways. While a pain to code up, it does provide the most seamless and expected functionality for site admins.

**Comment by mindctrl** [comment] 2017-02-27 19:06
👍 makes the most sense I think. will work on that after lunch.

**Comment by mindctrl** [comment] 2017-02-28 14:13
@nosegraze I think this is ready for testing.

**Comment by nosegraze** [comment] 2017-02-28 14:17
Spiffy, I'll get on it!

**Comment by mindctrl** [comment] 2017-02-28 14:22
I was trying to test payment failures last night, but the cards they list for testing failures were being accepted and charged as valid.

**Comment by nosegraze** [comment] 2017-02-28 14:38
Getting this error when trying to make a recurring subscription:

```
There was a problem processing your payment. Message: Plan ID is invalid.
```

**Comment by mindctrl** [comment] 2017-02-28 14:43
@nosegraze You have to create the plan in the Braintree web panel. Their API doesn't allow management of plans. The plan ID in Braintree must match the level ID in RCP.

**Comment by nosegraze** [comment] 2017-02-28 14:43
Wow that's shit. :P Hah, thanks.

**Comment by nosegraze** [comment] 2017-02-28 15:23
We'll either need to make a note about negative signup fees not working, or I wonder if we could get it working using Braintree's discounts? Looks like we'll need to do that for one-time discounts anyway?

**Comment by mindctrl** [comment] 2017-02-28 15:30
We'll either need to use Braintree's discounts or do a one-time payment followed by a subscription that starts at the end of the one-time payment period.

If we use Braintree's discount feature, that would not be consistent with how we chose to handle signup fees above.

**Comment by nosegraze** [comment] 2017-02-28 15:31
Ah I didn't realize you could override the subscription start date. That's a better idea.

**Comment by nosegraze** [comment] 2017-02-28 15:35
Completed all testing here https://github.com/restrictcontentpro/restrict-content-pro/issues/142#issuecomment-282121825 except one-time discounts! Everything worked great!

**Comment by nosegraze** [comment] 2017-02-28 22:28
Recurring one-time discounts works with your new changes.
Non-recurring needs a small fix to work (as noted on the PR).

I wonder if your code for signup fees and discounts could be combined by checking if `$this->amount` (recurring amount) and `$this->initial_amount` simply don't equal each other. If that's the case, then you can just have one block of code where you do a one-time payment and defer the start date of the subscription.

**Comment by mindctrl** [comment] 2017-02-28 22:37
Updated. Yeah, those can probably be combined. I did them at different times and kept things separate to keep them clear in my head. Lots of moving parts with hacking around their API like this.

**Comment by mindctrl** [comment] 2017-03-01 15:05
@nosegraze I updated this and combined the single payment logic. Can you give this some eyes?

**Comment by nosegraze** [comment] 2017-03-01 15:12
Looks good on paper, though I *think* this line needs to account for signup fees as well: https://github.com/restrictcontentpro/restrict-content-pro/blob/dabf5af041aa39a77eb24cab11e741bf0644a23d/includes/gateways/class-rcp-payment-gateway-braintree.php#L273 Because the one-time payment is for the full amount, so the subscription should be delayed if there are signup fees as well. Maybe just replace that with another

```
if ( $this->initial_amount != $this->amount ) {
```

I'm going to re-run these tests just to be sure:

- [ ] One-time discount code, non-recurring.
- [ ] One-time discount code, recurring.
- [ ] Signup fee, non-recurring.
- [ ] Signup fee, recurring.

**Comment by nosegraze** [comment] 2017-03-01 15:19
One annoying thing:

- Upgrade subscription (previous subscription gets cancelled).
- Fail payment.
- Go back and try upgrade again.
- Get error that "Subscription has already been canceled" and you can't proceed with payment.

IMO it would be nice to avoid the `wp_die()` if the error message is that the subscription has already been cancelled.

**Comment by mindctrl** [comment] 2017-03-01 15:21
Yep, you're right about delaying sub with signup fee. Will update.

**Comment by mindctrl** [comment] 2017-03-01 15:26
I just found an issue. Digging into it.

**Comment by mindctrl** [comment] 2017-03-01 15:29
Ha you found the same one. Updating in a sec.

**Comment by mindctrl** [comment] 2017-03-01 15:39
updated

**Comment by nosegraze** [comment] 2017-03-01 15:41
Tested the above 4 registrations and everything worked well!

**Comment by mindctrl** [comment] 2017-03-01 15:46
Great! Looking at the cancel issue you saw, to see about not failing if it's already cancelled.

**Comment by mindctrl** [comment] 2017-03-01 16:43
Updated to not die when subscription is already cancelled.

**Comment by nosegraze** [comment] 2017-03-01 17:54
Confirmed it's fixed!

Small thing, but perhaps this should be `wp_die()` https://github.com/restrictcontentpro/restrict-content-pro/blob/84790fe9b852c10e4a99744a2b869d5af1e11db1/includes/gateways/class-rcp-payment-gateway-braintree.php#L626

**Comment by mindctrl** [comment] 2017-03-01 18:11
Updated to use `wp_die()`

**Comment by mindctrl** [comment] 2017-03-01 18:20
Merged!

**Closed by mindctrl** 2017-03-01 18:20 UTC
Labels: enhancement, has PR, needs testing
