### ISSUE TITLE
Feature Request: Multiple Reminder Emails

### ISSUE THREAD

**Issue by psorensen** [restrictcontentpro/restrict-content-pro#984] opened 2017-02-17 00:18 UTC
Getting requests from clients to include multiple expiration reminder emails. e.g send expiration warning at 1 week, 3 days,  and 1 day before expiration.

**Comment by mindctrl** [comment] 2017-02-17 16:09
Related: https://github.com/restrictcontentpro/restrict-content-pro/issues/558

**Comment by mindctrl** [comment] 2017-03-13 19:39
Got another request for this.

**Comment by pippinsplugins** [comment] 2017-04-27 14:08
Closing this as a duplicate of https://github.com/restrictcontentpro/restrict-content-pro/issues/558

**Closed by pippinsplugins** 2017-04-27 14:08 UTC
Labels: duplicate, enhancement
