### ISSUE TITLE
Sluggish Queries

### ISSUE THREAD

**Issue by bearded-avenger** [restrictcontentpro/restrict-content-pro#135] opened 2015-03-16 14:36 UTC
Pippin,
Here's those slow queries from CGC (10+ seconds to compute):

https://gist.github.com/bearded-avenger/259c94bcf1073fa95161

**Comment by pippinsplugins** [comment] 2015-03-18 21:37
Thanks @bearded-avenger, I'm digging into these!

**Comment by etcook** [comment] 2015-03-21 02:22
@pippinsplugins Here's another set:

https://gist.github.com/etcook/5b5f165881da955b72b3

Thanks!

**Comment by pippinsplugins** [comment] 2015-03-26 00:24
Thanks guys, I'll be looking at these soon.

**Comment by pippinsplugins** [comment] 2015-04-03 14:33
@etcook @bearded-avenger Do either of you know where this query is originating?
```mysql
SELECT payments, COUNT(*) AS freq
 
FROM
 
(
 
    SELECT user.ID,
 
    user.user_login, 
 
    COUNT(p.id) AS payments
 
    FROM net_users user
 
    LEFT JOIN net_usermeta AS um1 ON user.ID = um1.user_id
 
    LEFT JOIN net_usermeta AS um2 ON user.ID = um2.user_id
 
    LEFT JOIN rcp_payments AS p ON user.ID = p.user_id
 
    WHERE um1.meta_key = 'rcp_status'
 
    AND um1.meta_value = 'expired'
 
    AND um2.meta_key = 'rcp_subscription_level'
 
    AND um2.meta_value = 6
 
    GROUP BY user.ID
 
) AS numbers
 
GROUP BY payments;
```

That doesn't exist anywhere in RCP.

Is that in the user experience plugin on CGC perhaps?

**Comment by bearded-avenger** [comment] 2015-04-03 14:40
Good question. I ran a search for rcp_subscription_level across all themes, and XP Dashboard, and I don't see anything. I can safely say I would have never formed a query like that, so if it is in our codebase, it would have been something that was introduced before 2014.

Does that ring any bells? Any RCP helper plugins for CGC? I'm still looking.

**Comment by pippinsplugins** [comment] 2015-04-03 14:40
Can you link me to the XP Dashboard file that has similar queries in it? I vaguely recall Ti helping to write some like that.

**Comment by bearded-avenger** [comment] 2015-04-03 14:41
One sec, that was for the rank views though....

**Comment by bearded-avenger** [comment] 2015-04-03 14:41
https://github.com/CGCookie/cgc-xp-dashboard

xp dashboard doesnt call anything for RCP

**Comment by ryanduff** [comment] 2015-04-03 14:43
Only place I saw anything related in RCP was the nested meta queries here. Though not sure it'd generate that output. 

https://github.com/pippinsplugins/Restrict-Content-Pro/blob/aaa643114df391cec68af1ad260ce5f209e11f63/includes/member-functions.php#L73-169

Can you run debug bar w/ savequeries to see where it originates?

**Comment by bearded-avenger** [comment] 2015-04-03 14:44
Pippin I"m almost 100% positive this isn't in our codebase, I'd be super surprised if it was. I"m continuing the search.

**Comment by bearded-avenger** [comment] 2015-04-03 14:45
@ryanduff thanks, that looks like it's it actually?

**Comment by pippinsplugins** [comment] 2015-04-12 18:44
@bearded-avenger I can't find anything for this in RCP or CGC. Are there any plugins (related to RCP or user accounts) running on the CGC site that are not on Github?

**Comment by bearded-avenger** [comment] 2015-04-12 18:50
There are definitely no plugins on staging and production that are not under version control.

@etcook are we able to trace this query down to the file it's originating from?

@pippinsplugins is this not it? https://github.com/pippinsplugins/Restrict-Content-Pro/blob/aaa643114df391cec68af1ad260ce5f209e11f63/includes/member-functions.php#L73-169

**Comment by pippinsplugins** [comment] 2015-04-12 22:18
That is a slow query but it's not the one I was referencing above: https://github.com/pippinsplugins/Restrict-Content-Pro/issues/135#issuecomment-89304951

**Comment by bearded-avenger** [comment] 2015-04-12 22:37
Let me run through again. If it's not in RCP it has to be in the mountain of a codebase that is CGC 4.

**Comment by pippinsplugins** [comment] 2015-04-24 19:49
@bearded-avenger any luck finding it?

**Comment by bearded-avenger** [comment] 2015-04-24 19:54
Nopers.

I'm hand pruning all code that goes into FIVE as I'm building it, so I think one way to tell is to see if this query is still present when FIVE goes live. If it IS present, we know it's NOT in our codebase.

I can't think of any query that would be specifically pulling the expired status from a level 6 rcp meta object.

Is it possible this is remnants from leaving amember? Maybe part of an upgrade script written before 2014?

**Comment by nosegraze** [comment] 2017-03-14 13:02
I got a report of the query in `rcp_get_restricted_post_ids()` being extremely slow. I think this guy has a ton of posts and is publishing often, which means the transient is being deleted often and the query gets run (and even times out) a lot.

**Comment by mindctrl** [comment] 2017-03-14 13:51
@nosegraze can we get a login to the site having this problem?

**Comment by nosegraze** [comment] 2017-06-16 15:11
Another report about `rcp_get_restricted_post_ids()` :  https://secure.helpscout.net/conversation/382295808/61234/?folderId=841776

**Comment by mindctrl** [comment] 2017-06-16 19:39
I haven't though through all this yet, but maybe we should consider migrating all post meta things we have to query against over to taxonomies. A lot of the post meta we use isn't really designed for post meta use. The values are the same, or one of a set number of known values. Dunno, something to think about.

**Comment by nosegraze** [comment] 2017-06-19 09:18
Didn't WooCommerce recently do something similar?

I'm definitely open to any ideas here. I don't really think our current method is a great/sustainable option for large sites, particularly if they publish new posts frequently (meaning the transient is constantly deleted and the query re-runs often) and they aren't on great hosting.

**Comment by pippinsplugins** [comment] 2017-06-21 13:55
We did this in EDD Commissions. It's pretty simple to do.

**Comment by mindctrl** [comment] 2017-07-17 18:58
Another report of slow queries on a site that has **106 million** rows in the tables that get joined for these meta queries.

I'm pretty sure the original reason this issue was opened was for a different query entirely, but we can keep this here if we want.

**Comment by nosegraze** [comment] 2017-08-10 15:39
Another report. Someone with a SiteGround site was given a "resource limit" on their account due to the slow query for getting restricted posts consuming too many resources.

**Comment by Pls** [comment] 2017-12-19 14:06
Any thoughts on how to solve this problem? Or maby you guys have thought of better implementation to sovle this? We are expieriencing similar problems with rcp_get_restricted_post_ids() executing with costly resources.

**Comment by mindctrl** [comment] 2017-12-19 14:11
We're going to look at moving our post meta dependencies to taxonomy terms. Currently slated for version 3.1.

**Comment by joewa1980** [comment] 2018-01-21 23:44
@pippinsplugins https://github.com/restrictcontentpro/restrict-content-pro/issues/135#issuecomment-89304951 - that's exactly the code being sent with every save of our custom post types. We've only noticed this in the past two days and looking back at our error.log it has been causing significant CPU overloads for us **since... 2014**. Yikes!

I can confirm that when users hit publish/draft the query is activated and begins its journey munching on **126m rows**. Nice. This usually takes over 300s and with only 2-10 users our dedicated server is overloaded and grinds to a halt. 

Disabling RCP alleviates the problem totally. Is there a quickfix we can apply to our two production sites before you release 3.1? It's caused untold stress this end with paying customers and I'm SO pleased to have found this bug report!

**Comment by pippinsplugins** [comment] 2018-01-22 00:34
@joewa1980 the quick fix is to uncheck the option in Restrict > Settings > Misc for "Hide restricted content".

That will take care of the issue for the short term while we continue to work on the long term solution.

**Comment by joewa1980** [comment] 2018-01-22 14:51
Thanks @pippinsplugins - I look forward to the fix for peace of mind as well as for those classy redirections when a restricted page is hit, we value it for sales.

**Comment by mindctrl** [comment] 2018-03-25 18:59
Closing this in favor of https://github.com/restrictcontentpro/restrict-content-pro/issues/1736, since this was originally about something different that was never confirmed to be in RCP, and then became about post meta queries as the discussion went on.

**Closed by mindctrl** 2018-03-25 18:59 UTC
Labels: bug
