### ISSUE TITLE
Revamp CSS 

### ISSUE THREAD

**Issue by michaelbeil** [restrictcontentpro/restrict-content-pro#535] opened 2016-06-03 00:05 UTC
There a few things we could do to better our CSS:
- [ ] Change px to rem
- [x] Remove empty selectors
- [x] Should our CSS worth be minified?
- [x] Make our CSS more readable
- [x] Replace super generic class names in admin with prefixed class names
- [x] Remove RCP-Icons since it's not used

**Comment by pippinsplugins** [comment] 2016-06-03 01:09
Just added another.

**Comment by nosegraze** [comment] 2017-02-10 13:21
Correct me if I'm wrong, but it looks like we're loading the `RCP-Icons` font in `forms.css` but then not actually using it anywhere?

**Comment by mindctrl** [comment] 2017-02-10 16:13
I think you're right, I noticed that a couple weeks ago. I vote we double check that, and get rid of it if so.

**Comment by nosegraze** [comment] 2017-02-10 16:25
I did a few searches and the only result I found for setting the `font-family` to `RCP-Icons` was here:

```css
[class*="rcp-icon-"], [class*=" rcp-icon-"] {
    font-family: 'RCP-Icons';
```

So I did a search for `rcp-icon` and there weren't any outside of the CSS file, so that class doesn't seem to be used anywhere.

**Comment by mindctrl** [comment] 2017-02-10 17:05
Confirmed. Added removing RCP-Icons to the list up top.

**Comment by pippinsplugins** [comment] 2017-02-10 17:35
:+1:

**Comment by nosegraze** [comment] 2017-02-14 16:28
WIP PR: #966

Did a code format on it so it looks like there are more changes than there are. :P

- Added some nice section and file headers.
- Tried to make spacing and bracket placement more consistent.
- Removed `@font-face` and associated classes from the CSS, though I haven't actually deleted the font files.
- Removed a small amount of duplicate code.
- Did some reorganizing to try to group similar items together.

Still needs more work and a more thorough look over.

**Comment by pippinsplugins** [comment] 2017-02-14 17:33
Looking  good so far 🎉

**Comment by mindctrl** [comment] 2017-02-14 18:13
Yay, looking good!

Nitpicky, but I'd prefer to keep tabs instead of moving to spaces. Just converting the existing files to tabs shaves over 600 bytes off `admin-styles.css` and around 300 bytes off `forms.css`... and tabs are consistent with our PHP and JS indentation.

**Comment by pippinsplugins** [comment] 2017-02-14 21:32
>>>Nitpicky, but I'd prefer to keep tabs instead of moving to spaces.

Tabs for indention please :)

**Comment by nosegraze** [comment] 2017-02-15 12:22
Updated with tabs!

**Closed** 2017-02-23 20:58 UTC
Labels: enhancement
