### ISSUE TITLE
Bug: RCP 1.8 Prorating is not applied with Paypal Std

### ISSUE THREAD

**Issue by lordspace** [restrictcontentpro/restrict-content-pro#1084] opened 2017-03-12 12:54 UTC
I am testing RCP on my staging server (text in in Cyrillic) and no prorating is applied.

User signs up for plus plan at 5 Euro/m
a 20 minutes later upgrades to Plus (yearly) plan at 50 Euro/year.
The second subscription should have been at 45 for the first year and 50 EUR afterwards.

![image](https://cloud.githubusercontent.com/assets/137558/23831909/fb19bdba-0732-11e7-88a5-5061911939a5.png)

**Comment by mindctrl** [comment] 2017-03-13 21:51
@lordspace did the member select auto-renew during the first purchase?

**Comment by lordspace** [comment] 2017-03-14 22:07
The auto-renew has been set to always yes so the user is not prompted for that.

**Comment by mindctrl** [comment] 2017-03-30 14:20
Closing this. We can reopen if needed.

**Closed by mindctrl** 2017-03-30 14:20 UTC
Labels: bug

**Comment by lordspace** [comment] 2017-04-03 10:44
have you fixed it? Because I am still not seeing any prorating with 1.8.3 still.
I just tested this on my staging server.

**Comment by nosegraze** [comment] 2017-04-03 10:47
@lordspace Please send us a message through [our support page](https://restrictcontentpro.com/support/) so we can help you with this. Thusfar we've been unable to reproduce it on our own so we may need to work with you a bit more to see if it's an issue with your setup/environment. Same goes for your issue with PayPal Express.

**Comment by lordspace** [comment] 2017-04-03 11:07
Ok.
